spring:
  application:
    name: Agent

  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        model: deepseek-v4-pro

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  tomcat:
    max-http-form-post-size: 20MB
